### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ghost** [minoh0201/DeepMicro#2]
Hello,I was trying to reproduce the experiments described in the paper from the given data.
command:
`python DM.py -r 1 -cd UserDataExample.csv -cl UserLabelExample.csv -m svm`

I got these errors

Epoch 00328: early stopping
Traceback (most recent call last):
  File "DM.py", line 718, in <module>
    run_exp(args.seed)
  File "DM.py", line 660, in run_exp
    latent_act=args.ae_lact, output_act=args.ae_oact, patience=args.patience, no_trn=args.no_trn)
  File "DM.py", line 216, in ae
    self.autoencoder = load_model(modelName)
  File "/home/ubuntu/anaconda3/envs/deep_env/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/ubuntu/anaconda3/envs/deep_env/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'.

How can I solve it?
Thank you.

**Comment by gkrisp98** [comment]
I got the same errors when trying to use Deep Micro for mine dataset. 
Were you able to solve it ?

**Comment by paulzierep** [comment]
I think the problem is the h5py version: https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi
Using `pip install h5py==2.10.0 --force-reinstall` worked for me.
